/**
 * Research Domain Types
 * ──────────────────────
 * Type system for the Probex Research Terminal.
 *
 * Design principle: Research is NOT a blog.
 * It is a structured intelligence terminal — every report is
 * machine-readable, categorized, tagged, and cross-referenced
 * with the Consensus Engine and on-chain data.
 *
 * Report hierarchy:
 *   ResearchCategory → ResearchReport → ResearchSignal[]
 *
 * Reports are authored by the Probex Research Desk (human analysts)
 * or generated by the QUBO Consensus Engine (algorithmic).
 */

import type { BitcoinSegment, TimeRange } from './market'
import type { Bias, ConfidenceLevel, SignalLevel } from './consensus'

/** Alias for ConfidenceLevel — used in research filter components */
export type ResearchConfidence = ConfidenceLevel
import type { ReportId } from './branded'

// ─── Category and Type ────────────────────────────────────────────────────

export type ResearchCategoryId =
  | 'btc-outlook'
  | 'consensus-report'
  | 'etf-monitor'
  | 'institutional-activity'
  | 'on-chain-signals'
  | 'macro-signals'
  | 'market-structure'
  | 'volatility-analysis'
  | 'segment-deep-dive'
  | 'weekly-brief'

export type ResearchFormat =
  | 'report'        // long-form written analysis
  | 'signal-brief'  // machine-generated consensus signal summary
  | 'data-brief'    // chart + data-heavy, minimal prose
  | 'outlook'       // directional forecast
  | 'monitor'       // ongoing tracking (ETF, flows)
  | 'alert'         // time-sensitive signal update

export type ResearchSentiment = 'strongly-bullish' | 'bullish' | 'neutral' | 'bearish' | 'strongly-bearish'

export type ResearchStatus = 'published' | 'updated' | 'superseded' | 'archived'

// ─── Author ───────────────────────────────────────────────────────────────

export type ResearchAuthorType = 'analyst' | 'consensus-engine' | 'quant-model'

export interface ResearchAuthor {
  id:        string
  handle:    string    // e.g. "@probex-alpha-desk"
  name:      string
  type:      ResearchAuthorType
  avatarLabel: string  // initials or emoji for avatar
}

// ─── Research Signal ──────────────────────────────────────────────────────

/**
 * A structured intelligence signal embedded in or extracted from a report.
 * Signals are machine-readable and can be cross-referenced with markets.
 */
export interface ResearchSignal {
  id:             string
  type:           'bullish-flag' | 'bearish-flag' | 'watch' | 'key-level' | 'catalyst'
  label:          string
  description:    string
  relevantMarkets: string[]   // market IDs
  strength:       SignalLevel
  confidence:     ConfidenceLevel
  expiresAt?:     string      // ISO — signal becomes stale after this date
}

// ─── Research Source ──────────────────────────────────────────────────────

export interface ResearchSource {
  label:  string
  type:   'on-chain' | 'etf-data' | 'macro-data' | 'market-data' | 'consensus-engine' | 'public'
  url?:   string
}

// ─── Key Thesis ───────────────────────────────────────────────────────────

export interface ResearchThesis {
  statement:    string        // one-sentence thesis
  confidence:   ConfidenceLevel
  timeHorizon:  TimeRange
  supportingFactors: string[]
  risks:        string[]
}

// ─── Research Report ──────────────────────────────────────────────────────

export interface ResearchReport {
  id:              ReportId
  title:           string
  subtitle?:       string
  categoryId:      ResearchCategoryId
  format:          ResearchFormat
  status:          ResearchStatus

  /** Primary directional view of the report */
  sentiment:       ResearchSentiment
  confidence:      ConfidenceLevel

  /** Segments this report is relevant to */
  relevantSegments: BitcoinSegment[]

  /** The primary thesis */
  thesis:          ResearchThesis

  /** Executive summary (2–3 sentences) */
  summary:         string

  /** Full report body (markdown-compatible prose) */
  body:            string

  /** Key bullets for the overview panel */
  keyPoints:       string[]

  /** Embedded intelligence signals */
  signals:         ResearchSignal[]

  /** Data sources referenced */
  sources:         ResearchSource[]

  author:          ResearchAuthor
  tags:            string[]

  publishedAt:     string    // ISO
  updatedAt:       string    // ISO
  estimatedReadMinutes: number

  /** Consensus Engine score at time of publication */
  consensusScoreAtPublication?: number

  /** Which market IDs are directly discussed */
  featuredMarkets: string[]
  // Convenience aliases — optionally populated by the mock factory and service
  // layer; absent on raw report fixtures, so consumers must treat them as
  // optional (e.g. `report.segments ?? []`).
  category?:    string              // alias for categoryId (display use)
  segment?:     BitcoinSegment | null  // primary segment (first of relevantSegments or null)
  segments?:    BitcoinSegment[]    // alias for relevantSegments
  readTime?:    number              // alias for estimatedReadMinutes (minutes)
}

// ─── Specialized Report Variants ──────────────────────────────────────────

/** Weekly market brief — always format='weekly-brief' */
export interface WeeklyBrief extends ResearchReport {
  format:          'signal-brief'
  weekNumber:      number
  year:            number
  marketHighlights: Array<{
    marketId:    string
    marketTitle: string
    note:        string
    sentiment:   ResearchSentiment
  }>
}

/** ETF monitoring report */
export interface ETFReport extends ResearchReport {
  categoryId:     'etf-monitor'
  etfMetrics: {
    weeklyNetInflow:  number   // USD millions
    topProduct:       string
    topProductFlow:   number
    cumulativeAum:    number   // USD billions
    inflowStreak:     number   // consecutive positive weeks
  }
}

/** BTC macro outlook report */
export interface MacroReport extends ResearchReport {
  categoryId:       'macro-signals'
  macroFactors: Array<{
    factor:    string
    direction: Bias
    weight:    'high' | 'medium' | 'low'
  }>
}

/** Consensus intelligence report */
export interface ConsensusReport extends ResearchReport {
  categoryId:          'consensus-report'
  engineMetrics: {
    avgScore:          number
    signalStrength:    SignalLevel
    instRetailDivergence: number   // 0 = fully aligned, 1 = fully divergent
    marketsCoverage:   number
  }
}

// ─── Research Discovery / Filtering ──────────────────────────────────────

export interface ResearchFilters {
  categoryId?:   ResearchCategoryId | undefined
  format?:       ResearchFormat | undefined
  sentiment?:    ResearchSentiment | undefined
  confidence?:   ConfidenceLevel | undefined
  search?:       string | undefined
  segment?:      BitcoinSegment | undefined
  tags?:         string[] | undefined
  sortBy?:       'publishedAt' | 'confidence' | 'readTime' | undefined
  sortDir?:      'asc' | 'desc' | undefined
  limit?:        number | undefined
}

export interface ResearchCategory {
  id:          ResearchCategoryId
  label:       string
  description: string
  iconLabel:   string   // emoji or short text for icon badge
}

// ─── Research Terminal State ───────────────────────────────────────────────

export interface ResearchPageState {
  activeCategory:  ResearchCategoryId | null
  activeReportId:  ReportId | null
  savedReportIds:  ReportId[]
  searchQuery:     string
  sortBy:          'publishedAt' | 'confidence' | 'readTime'
  sortDir:         'asc' | 'desc'
}
