export { getContractAddresses, getContractAddress } from './addresses'

/**
 * ABI files live in ./abis/*.json
 * Imported by contract hooks in /hooks/ when needed.
 *
 * Example:
 *   import ProbexMarketABI from './abis/ProbexMarket.json'
 *
 * ABIs are generated by the contracts team from Solidity compilation.
 * Placeholder .json files will be committed once contracts are deployed.
 */
